apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      labels:
        app: agri-backend
    spec:
      containers:
        - name: backend
          image: agri-backend:v2
          imagePullPolicy: Never # Crucial for local Docker Desktop images
          env:
          - name: DB_HOST
            value: "postgres-service"
          - name: MONGO_HOST
            value: "mongodb-service"
---
apiVersion: v1
kind: Service
metadata:
  name: agri-backend-service
spec:
  selector:
    app: agri-backend
  ports:
    - protocol: TCP
      port: 80       # Port accessible from outside
      targetPort: 8080 # Port inside the container
  type: LoadBalancer # Docker Desktop will map this to localhost:80