name: assignment_project_agri_pl
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.5.9       #  Polyglot Persistence (SQL)
  mongo_dart: ^0.10.5     # Polyglot Persistence (NoSQL)
  uuid: ^4.5.2           # For tracing/correlation IDs
  retry: ^3.1.2          #  Resilience logic
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
