apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
      labels:
        app: agri-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: MONGO_HOST
              value: "mongodb-service"