apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      labels:
        app: agri-backend
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/metrics"
          prometheus.io/port: "8080"
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
          - name: DB_HOST
            value: "postgres-service"
          - name: MONGO_HOST
            value: "mongodb-service"
---
apiVersion: v1
kind: Service
metadata:
  name: agri-backend-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: agri-backend
  ports:
    - protocol: TCP
      port: 80       # Port accessible from outside
      targetPort: 8080 # Port inside the container
  type: LoadBalancer # Docker Desktop will map this to localhost:80